# Site settings
title: Tritia Timmins
email: tritialtimmins@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 The online portfolio of Tritia Timmins. UX Designer and Blogger.
# baseurl: "/Ion-Jekyll-Theme" # the subpath of your site, e.g. /blog/
baseurl: "/"
url: "http://tritiatimmins.com" # the base hostname & protocol for your site
twitter_username: tritialitimmins
github_username:  tritiatimmins

# Build settings
markdown: kramdown
